services:
  app:
    image: python:3.11-slim-bookworm
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "pip install -r requirements.txt && streamlit run app/main.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - "8501:8501"
